import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts", "tests/**/*.test.cjs"],
    environment: "node",
    // Disable cross-file parallelism. The CLA preflight-drift tests mutate
    // knowledge/cla-routing-keywords.yaml on disk; running in parallel with
    // tests/validate-tier1.test.ts (which reads the same file) causes
    // intermittent failures. Within a file vitest still runs tests in order.
    fileParallelism: false,
    coverage: {
      provider: "v8",
      reporter: ["text", "html"],
      include: [
        "supabase/functions/_shared/**/*.ts",
        "scripts/validate-tier1.cjs",
        "scripts/wave2-bundle-schedules.cjs",
      ],
      exclude: [
        "supabase/functions/scheduled-run-dispatcher/index.ts", // Deno-only entry point
        "supabase/functions/minion-worker/index.ts",            // Deno-only entry point
        "supabase/functions/_shared/schedules.generated.ts",    // auto-generated by bundler
      ],
    },
  },
});
