#!/usr/bin/env node
/**
 * scripts/init.cjs — agent-os init wizard
 *
 * Run: pnpm init  (or: node scripts/init.cjs)
 * Reset: node scripts/init.cjs --reset
 *
 * Walks the founder through customizing the agent-os boilerplate for a new
 * organization. Substitutes ${PLACEHOLDER} variables across Tier 1 files,
 * pre-fills runtime/secrets/.env.local, and writes .wizard-history.md.
 *
 * Idempotent: re-runs without --reset exit early. Substitutions are NOT
 * reversible — once ${ORG_NAME} becomes the user's value, the placeholder
 * is gone unless re-extracted from the boilerplate.
 *
 * The wizard does NOT:
 *   - Apply Supabase migrations (DEPLOY.md does, with HITL gating)
 *   - Provision Supabase projects (founder does, in dashboard)
 *   - Push to GitHub (founder does)
 *   - Read or write secrets to any external secret manager
 */

const fs = require("fs");
const path = require("path");
const readline = require("readline");
const { execSync } = require("child_process");

const ROOT = path.resolve(__dirname, "..");
const HISTORY_PATH = path.join(ROOT, ".wizard-history.md");
const ENV_EXAMPLE = path.join(ROOT, ".env.example");
const ENV_LOCAL_TARGET = path.join(ROOT, "runtime", "secrets", ".env.local");
const ARGS = new Set(process.argv.slice(2));

// ---------- helpers ----------

function rl() {
  return readline.createInterface({ input: process.stdin, output: process.stdout });
}

function ask(question, defaultValue) {
  return new Promise((resolve) => {
    const r = rl();
    const prompt = defaultValue ? `${question} [${defaultValue}]: ` : `${question}: `;
    r.question(prompt, (answer) => {
      r.close();
      resolve(answer.trim() || defaultValue || "");
    });
  });
}

async function askRequired(question, defaultValue) {
  while (true) {
    const v = await ask(question, defaultValue);
    if (v) return v;
    console.log("  ⚠ This field is required.");
  }
}

async function askMulti(question, options) {
  console.log(`\n${question}`);
  options.forEach((opt, i) => console.log(`  ${i + 1}) ${opt}`));
  const raw = await ask("Comma-separated numbers (e.g., 1,3,5)", "");
  if (!raw) return [];
  const idxs = raw.split(",").map((s) => parseInt(s.trim(), 10)).filter((n) => !isNaN(n));
  return idxs.map((i) => options[i - 1]).filter(Boolean);
}

function slugify(s) {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function snakeify(s) {
  return slugify(s).replace(/-/g, "_");
}

function uppercaseSlug(s) {
  return slugify(s).toUpperCase().replace(/-/g, "_");
}

function autoGithubOwner() {
  try {
    const out = execSync("gh api user --jq .login 2>/dev/null", { encoding: "utf8" }).trim();
    return out || "";
  } catch {
    return "";
  }
}

function detectTimezone() {
  try {
    return Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC";
  } catch {
    return "UTC";
  }
}

function loadHistory() {
  if (!fs.existsSync(HISTORY_PATH)) return null;
  try {
    const txt = fs.readFileSync(HISTORY_PATH, "utf8");
    const m = txt.match(/^status:\s*(.+)$/m);
    const orgM = txt.match(/^org_name:\s*(.+)$/m);
    return { status: m ? m[1].trim() : "unknown", orgName: orgM ? orgM[1].trim() : "" };
  } catch {
    return null;
  }
}

function writeHistory(config) {
  const ts = new Date().toISOString();
  const lines = [
    "# Wizard run history",
    "",
    `status: complete`,
    `completed_at: ${ts}`,
    `wizard_version: 0.1.0`,
    "",
    "## Inputs (sensitive values redacted)",
    "",
    `org_name: ${config.ORG_NAME}`,
    `org_slug: ${config.ORG_SLUG}`,
    `org_repo_name: ${config.ORG_REPO_NAME}`,
    `product_name: ${config.PRODUCT_NAME}`,
    `product_domain: ${config.PRODUCT_DOMAIN}`,
    `founder_name: ${config.FOUNDER_NAME}`,
    `founder_email: ${config.FOUNDER_EMAIL}`,
    `founder_timezone: ${config.FOUNDER_TIMEZONE}`,
    `primary_locale: ${config.PRIMARY_LOCALE}`,
    `github_owner: ${config.GITHUB_OWNER}`,
    `supabase_ops_project_ref: <REDACTED — see runtime/secrets/.env.local>`,
    `deployment_mode: ${config.DEPLOYMENT_MODE}`,
    `pillars_enabled: ${(config.PILLARS_ENABLED || []).join(", ")}`,
    "",
    "To re-run the wizard with new inputs: `node scripts/init.cjs --reset`",
    "",
    "Note: substitutions are NOT reversible. --reset re-asks questions but cannot",
    "restore the original ${PLACEHOLDER} text in files.",
  ];
  fs.writeFileSync(HISTORY_PATH, lines.join("\n") + "\n", "utf8");
}

// ---------- substitution (mirror of scripts/_extract/scrub.cjs in reverse direction) ----------

const SKIP_FILES = new Set([
  // The wizard's own files — leave alone
  "scripts/init.cjs",
  "scripts/_extract/scrub.cjs",
  ".wizard-history.md",
  // Generated files — regenerated by bundlers, no need to substitute
  "supabase/functions/_shared/schedules.generated.ts",
  "supabase/functions/_shared/invariants.generated.ts",
  "supabase/functions/_shared/manifest-tables.generated.ts",
]);

const SKIP_DIRS = new Set([
  ".git",
  "node_modules",
  "_build",
  "coverage",
  "runtime",
  "raw",
  ".archives",
]);

const TEXT_EXTS = new Set([
  ".md", ".yaml", ".yml", ".json", ".ts", ".tsx", ".js", ".cjs", ".mjs",
  ".sql", ".sh", ".env", ".example", ".toml", ".txt", ".gitignore", "",
]);

const TEXT_NAMES = new Set([".env.example", ".gitignore", ".nvmrc"]);

function buildSubstitutions(config) {
  const subs = [];
  // Order: longer keys first to avoid partial overrides (e.g., ORG_NAME before ORG)
  const orderedKeys = Object.keys(config).sort((a, b) => b.length - a.length);
  for (const key of orderedKeys) {
    const val = config[key];
    if (val == null || val === "" || Array.isArray(val)) continue;
    // Match ${KEY} as literal text in any file
    const escaped = key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    subs.push({
      find: new RegExp("\\$\\{" + escaped + "\\}", "g"),
      replace: String(val),
      key,
    });
  }
  return subs;
}

function walk(dir, rel = "") {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    const r = path.join(rel, entry.name);
    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name) || SKIP_DIRS.has(r)) continue;
      out.push(...walk(full, r));
    } else if (entry.isFile()) {
      out.push({ full, rel: r });
    }
  }
  return out;
}

function applySubstitutions(config) {
  const subs = buildSubstitutions(config);
  const files = walk(ROOT);
  let touched = 0;
  let replaced = 0;
  const report = [];

  for (const { full, rel } of files) {
    if (SKIP_FILES.has(rel)) continue;
    const ext = path.extname(full);
    const base = path.basename(full);
    if (!TEXT_EXTS.has(ext) && !TEXT_NAMES.has(base)) continue;
    let content;
    try {
      content = fs.readFileSync(full, "utf8");
    } catch {
      continue;
    }
    if (content.indexOf("\0") !== -1) continue;
    let modified = content;
    let count = 0;
    for (const s of subs) {
      const m = modified.match(s.find);
      if (m && m.length) {
        count += m.length;
        modified = modified.replace(s.find, s.replace);
      }
    }
    if (modified !== content) {
      fs.writeFileSync(full, modified, "utf8");
      touched += 1;
      replaced += count;
      report.push({ file: rel, count });
    }
  }
  return { touched, replaced, report };
}

// ---------- env.local generation ----------

function generateEnvLocal(config) {
  if (!fs.existsSync(ENV_EXAMPLE)) {
    console.log("  ⚠ .env.example not found; skipping .env.local generation");
    return false;
  }
  const example = fs.readFileSync(ENV_EXAMPLE, "utf8");
  // Apply substitutions to env example content too
  const subs = buildSubstitutions(config);
  let envContent = example;
  for (const s of subs) envContent = envContent.replace(s.find, s.replace);

  // Pre-fill known secrets that came from wizard
  const PREFILL = {
    AGENT_OS_DEPLOYMENT_MODE: config.DEPLOYMENT_MODE,
    AGENT_OS_LOCALE_DEFAULT: config.PRIMARY_LOCALE,
    AGENT_OS_TIMEZONE: config.FOUNDER_TIMEZONE,
    SUPABASE_URL: `https://${config.SUPABASE_OPS_PROJECT_REF}.supabase.co`,
  };
  for (const [k, v] of Object.entries(PREFILL)) {
    if (!v) continue;
    const re = new RegExp(`^${k}=.*$`, "m");
    if (re.test(envContent)) {
      envContent = envContent.replace(re, `${k}=${v}`);
    } else {
      envContent += `\n${k}=${v}\n`;
    }
  }

  fs.mkdirSync(path.dirname(ENV_LOCAL_TARGET), { recursive: true });
  fs.writeFileSync(ENV_LOCAL_TARGET, envContent, "utf8");
  // Symlink at root (matches existing bootstrap.sh convention)
  const symlink = path.join(ROOT, ".env.local");
  try {
    if (fs.lstatSync(symlink).isSymbolicLink()) fs.unlinkSync(symlink);
  } catch {}
  try {
    fs.symlinkSync("runtime/secrets/.env.local", symlink);
  } catch {}
  return true;
}

// ---------- pillar pruning ----------

const ALL_PILLARS = [
  "01-growth",
  "02-customer",
  "03-product",
  "04-content",
  "06-finance",
  "07-compliance",
  "08-integrations",
];

function prunePillars(enabled) {
  const removed = [];
  for (const pillar of ALL_PILLARS) {
    if (enabled.includes(pillar)) continue;
    const pillarDir = path.join(ROOT, pillar);
    if (!fs.existsSync(pillarDir)) continue;
    // Safety: only remove if it contains README.md and nothing else (or only README)
    const contents = fs.readdirSync(pillarDir);
    const onlyReadme = contents.length === 0 || (contents.length === 1 && contents[0] === "README.md");
    if (onlyReadme) {
      fs.rmSync(pillarDir, { recursive: true, force: true });
      removed.push(pillar);
    } else {
      console.log(`  ⚠ Pillar ${pillar} has more than just README — refusing to delete. Skip manually if needed.`);
    }
  }
  return removed;
}

// ---------- smoke test ----------

function runSmokeTest() {
  const checks = [
    { name: "pnpm validate", cmd: "pnpm validate" },
    { name: "pnpm test", cmd: "pnpm test --reporter=basic 2>&1 | tail -10" },
  ];
  const results = [];
  for (const { name, cmd } of checks) {
    try {
      execSync(cmd, { stdio: "pipe", cwd: ROOT });
      results.push({ name, status: "PASS" });
    } catch (err) {
      results.push({ name, status: "FAIL", error: err.message ? err.message.slice(0, 200) : "unknown" });
    }
  }
  return results;
}

// ---------- main ----------

async function main() {
  console.log("");
  console.log("==========================================================================");
  console.log("  agent-os init wizard");
  console.log("==========================================================================");
  console.log("");

  const history = loadHistory();
  if (history && history.status === "complete" && !ARGS.has("--reset")) {
    console.log(`  ✓ Wizard already complete for "${history.orgName}".`);
    console.log("  To re-run with new inputs: node scripts/init.cjs --reset");
    console.log("");
    process.exit(0);
  }

  if (ARGS.has("--reset") && history) {
    console.log("  ⚠ --reset will re-run wizard. Substitutions in files are NOT reversible.");
    console.log(`     Current org: ${history.orgName}`);
    const confirm = await ask("  Type the current org name to confirm reset", "");
    if (confirm !== history.orgName) {
      console.log("  Org name didn't match. Aborting.");
      process.exit(1);
    }
  }

  // ---- collect inputs ----

  console.log("Step 1/4 — Identity");
  console.log("");
  const ORG_NAME = await askRequired("Organization name (e.g., \"AI Film Studio\")");
  const ORG_SLUG = await askRequired("Organization slug (URL-safe)", slugify(ORG_NAME));
  const ORG_REPO_NAME = await askRequired("This repo's name", `${ORG_SLUG}-os`);
  const ORG_TAGLINE = await askRequired("Tagline (one-line, no period)", `${ORG_NAME} operating substrate`);
  const ORG_CATEGORY = await askRequired("Category", "AI-native organization");
  const ORG_EVENT_NS = await askRequired("Event namespace prefix", snakeify(ORG_NAME));
  const PRODUCT_NAME = await askRequired("Product name (often = org name)", ORG_NAME);
  const PRODUCT_DOMAIN = await askRequired("Product domain (e.g., scriptforge.ai)", `${ORG_SLUG}.ai`);
  const PRIMARY_EMAIL_DOMAIN = await askRequired("Primary email domain", PRODUCT_DOMAIN);

  console.log("");
  console.log("Step 2/4 — Founder");
  console.log("");
  const FOUNDER_NAME = await askRequired("Founder name");
  const FOUNDER_EMAIL = await askRequired("Founder email", `${slugify(FOUNDER_NAME).replace(/-/g, ".")}@${PRIMARY_EMAIL_DOMAIN}`);
  const FOUNDER_TIMEZONE = await askRequired("Founder timezone (IANA)", detectTimezone());
  const FOUNDER_SLUG = slugify(FOUNDER_NAME);
  const PRIMARY_LOCALE = await askRequired("Primary locale (e.g., en, vi, fr)", "en");
  const PRIMARY_LOCALE_FULL = await askRequired("Primary locale full (e.g., en-US, vi-VN)", `${PRIMARY_LOCALE}-${PRIMARY_LOCALE.toUpperCase()}`);
  const GITHUB_OWNER = await askRequired("GitHub owner / org", autoGithubOwner());

  console.log("");
  console.log("Step 3/4 — Supabase ops project");
  console.log("");
  console.log("(Create the project first at https://supabase.com/dashboard/projects, then paste its ref here.)");
  const SUPABASE_OPS_PROJECT_REF = await askRequired("Ops Supabase project ref (e.g., abcd1234efgh5678)");
  const SUPABASE_OPS_PROJECT_NAME = await askRequired("Ops Supabase project name (slug)", `${ORG_SLUG}-ops`);
  const SUPABASE_OPS_PROJECT_NAME_SNAKE = snakeify(SUPABASE_OPS_PROJECT_NAME);
  const SUPABASE_PRODUCT_PROJECT_REF = await ask("(Optional) Product Supabase project ref", "PRODUCT_PROJECT_REF_NOT_SET");
  const SUPABASE_PRODUCT_PROJECT_NAME = await ask("(Optional) Product Supabase project name", PRODUCT_NAME.toLowerCase());
  const OPS_REGION = await askRequired("Supabase ops region (e.g., us-west-1, ap-south-1)", "us-east-1");
  const OPS_REGION_HUMAN = await ask("Region (human-readable)", OPS_REGION);
  const DEPLOYMENT_MODE = (await ask("Deployment mode (local/production)", "local")).toLowerCase();

  console.log("");
  console.log("Step 4/4 — Pillars");
  console.log("");
  const pillarChoices = ALL_PILLARS;
  const PILLARS_ENABLED = await askMulti("Which pillars do you want to keep? (others will be removed)", pillarChoices);
  if (PILLARS_ENABLED.length === 0) {
    console.log("  ⚠ No pillars selected — keeping ALL pillars (you can manually delete later).");
    PILLARS_ENABLED.push(...pillarChoices);
  }

  const ORG_SLUG_UPPER = uppercaseSlug(ORG_SLUG);
  const YEAR = String(new Date().getFullYear());

  const config = {
    ORG_NAME,
    ORG_SLUG,
    ORG_SLUG_UPPER,
    ORG_REPO_NAME,
    ORG_TAGLINE,
    ORG_CATEGORY,
    ORG_EVENT_NS,
    PRODUCT_NAME,
    PRODUCT_DOMAIN,
    PRIMARY_EMAIL_DOMAIN,
    FOUNDER_NAME,
    FOUNDER_EMAIL,
    FOUNDER_TIMEZONE,
    FOUNDER_SLUG,
    PRIMARY_LOCALE,
    PRIMARY_LOCALE_FULL,
    GITHUB_OWNER,
    SUPABASE_OPS_PROJECT_REF,
    SUPABASE_OPS_PROJECT_NAME,
    SUPABASE_OPS_PROJECT_NAME_SNAKE,
    SUPABASE_PRODUCT_PROJECT_REF,
    SUPABASE_PRODUCT_PROJECT_NAME,
    OPS_REGION,
    OPS_REGION_HUMAN,
    DEPLOYMENT_MODE,
    PILLARS_ENABLED,
    YEAR,
  };

  console.log("");
  console.log("==========================================================================");
  console.log("Summary:");
  console.log(`  Org:       ${ORG_NAME} (${ORG_SLUG})`);
  console.log(`  Product:   ${PRODUCT_NAME} @ ${PRODUCT_DOMAIN}`);
  console.log(`  Founder:   ${FOUNDER_NAME} <${FOUNDER_EMAIL}> [${FOUNDER_TIMEZONE}]`);
  console.log(`  GitHub:    ${GITHUB_OWNER}`);
  console.log(`  Supabase:  ${SUPABASE_OPS_PROJECT_NAME} (${SUPABASE_OPS_PROJECT_REF}) in ${OPS_REGION}`);
  console.log(`  Mode:      ${DEPLOYMENT_MODE}`);
  console.log(`  Pillars:   ${PILLARS_ENABLED.join(", ")}`);
  console.log("==========================================================================");
  console.log("");
  const proceed = await ask("Proceed? (yes/no)", "yes");
  if (!/^y/i.test(proceed)) {
    console.log("Aborted.");
    process.exit(0);
  }

  // ---- apply substitutions ----

  console.log("");
  console.log("Applying substitutions...");
  const subResult = applySubstitutions(config);
  console.log(`  ✓ Touched ${subResult.touched} files, ${subResult.replaced} replacements.`);

  // ---- env.local ----

  console.log("");
  console.log("Generating runtime/secrets/.env.local...");
  const envOk = generateEnvLocal(config);
  if (envOk) {
    console.log(`  ✓ Wrote ${ENV_LOCAL_TARGET} (review and add ANTHROPIC_API_KEY etc.)`);
  }

  // ---- prune pillars ----

  console.log("");
  console.log("Pruning unselected pillars...");
  const removed = prunePillars(PILLARS_ENABLED);
  if (removed.length) {
    console.log(`  ✓ Removed: ${removed.join(", ")}`);
  } else {
    console.log("  ✓ No pillars removed (all kept or had non-default content).");
  }

  // ---- write history ----

  writeHistory(config);

  // ---- smoke test ----

  console.log("");
  console.log("Running smoke test...");
  const smoke = runSmokeTest();
  for (const r of smoke) {
    console.log(`  ${r.status === "PASS" ? "✓" : "✗"} ${r.name}: ${r.status}${r.error ? " — " + r.error : ""}`);
  }

  console.log("");
  console.log("==========================================================================");
  console.log("✅ Wizard complete.");
  console.log("==========================================================================");
  console.log("");
  console.log("Next steps:");
  console.log("  1. Review runtime/secrets/.env.local — add ANTHROPIC_API_KEY and other secrets.");
  console.log("  2. Open Claude Code: claude code .");
  console.log("  3. Paste DEPLOY.md contents into the session — the AI will walk you through Supabase provisioning.");
  console.log("  4. After deploy, see TODOS.md for first-mile work.");
  console.log("");
}

main().catch((err) => {
  console.error("Wizard failed:", err.message || err);
  process.exit(1);
});
